# Using environment parameters - Agent Level 0 
behaviors:
  TargetSeeker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 0.1
        gamma: 0.99
      gail:
        strength: 1
        gamma: 0.99
        demo_path: Demos/Demo-L1.demo
    behavioral_cloning:
      strength: 1
      demo_path: Demos/Demo-L1.demo
    max_steps: 3.0e6
    time_horizon: 64
    summary_freq: 10000

# Environment settings
environment_parameters:
  # Agent levels - 0,1,2,3,4
  agent_level: 1