# Using environment parameters - Agent Level 3 
behaviors:
  TargetSeeker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.2
      gail:
        gamma: 0.99
        strength: 0.5
        demo_path: Demos/NewDemo-L1.demo
    behavioral_cloning:
      steps: 50000
      strength: 0.5
      demo_path: Demos/NewDemo-L1.demo
    max_steps: 2.0e6
    time_horizon: 64
    summary_freq: 10000

# Environment settings
environment_parameters:
  # Agent levels - 0,1,2,3
  agent_level: 3