behaviors:
  TargetSeeker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 1
        gamma: 0.99
    max_steps: 2.0e6
    time_horizon: 64
    summary_freq: 10000

# Environment settings
environment_parameters:
  agent_level:
    curriculum:
      - name: FirstLesson
        completion_criteria:
          measure: progress
          behavior: TargetSeeker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 0
      - name: SecondLesson
        value: 1