behaviors:
  TargetSeeker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.1
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: Demos/Demo_L3.demo
    behavioral_cloning:
      strength: 1
      demo_path: Demos/Demo_L3.demo
    max_steps: 2.0e6
    time_horizon: 64
    summary_freq: 10000

# Environment settings
environment_parameters:
  agent_level:
    curriculum:
      - name: FirstLesson # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: TargetSeeker
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.2
        value: 0
      - name: SecondLesson # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: TargetSeeker
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.4
          require_reset: true
        value: 1
      - name: ThirdLesson # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: TargetSeeker
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 0.6
          require_reset: true
        value: 2
      - name: FourthLesson
        value: 3