behaviors:
  TargetSeeker:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 3.0e6
    time_horizon: 64
    summary_freq: 10000

# Environment settings
environment_parameters:
  agent_level:
    curriculum:
      - name: FirstLesson
        completion_criteria:
          measure: progress
          behavior: TargetSeeker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
        value: 0
      - name: SecondLesson
        completion_criteria:
          measure: progress
          behavior: TargetSeeker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
          require_reset: true
        value: 1
      - name: ThirdLesson
        completion_criteria:
          measure: progress
          behavior: TargetSeeker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.72
        value: 2
      - name: FourthLesson
        completion_criteria:
          measure: progress
          behavior: TargetSeeker
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.85
          require_reset: true
        value: 3
      - name: FifthLesson
        value: 4